### ISSUE TITLE
想了解刷新按键的实现和相关功能

### ISSUE THREAD

**Issue by Another5405** [PKM-er/Blue-topaz-example#70]
大佬好，小弟目前想利用黑耀石快速建立资料库
目前想在大佬的库中取经，改善DBMS的实现技术

因此想请教对此有帮助的相关插件，感谢。

**Comment by cumany** [comment]
刷新 按钮 其实是quickadd  实现 原理就是 关闭当前页面 再打开当前页面 就是刷新功能

**Comment by Another5405** [comment]
有，谢谢，我最近有了解到实行方法，
很意外Dataview的ForceReload目前有Bug，而你用的方法是关闭再开。
为查到这边的人补充一下，要实现自定义按键现在要用Commander。
