### ISSUE TITLE
【请教】如何定义微信样式的对话样式

### ISSUE THREAD

**Issue by AbnerPei** [PKM-er/Blue-topaz-example#71]
我安装了主题，也安装了插件，copy你的代码，并没有出现如下图的效果，请问需要怎么处理？
<img width="638" alt="image" src="https://user-images.githubusercontent.com/11939807/216814026-d26a2bb9-9e0c-43e2-9165-83885cb66597.png">

**Comment by cumany** [comment]
这个 在blue topaz 主题里的 style setting 3.7

**Comment by AbnerPei** [comment]
> 这个 在blue topaz 主题里的 style setting 3.7

非常感谢，找到了！
这个做自我反思（一个真实的自我，一个虚拟的自我），以对话的形式，实在是很好！
